language: generic
services:
  - docker

env:
  global:
    - UPSTREAM_WORKSPACE=github:ros-controls/ros2_control#crystal
  matrix:
    - ROS_DISTRO="crystal"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
